print(getwd())
setwd("F:")
data<-read.csv("input.csv")
print(data)
print(is.data.frame(data))
png(file="plotacc.jpg")
plot(data)
dev.off()
test1 <-data[,c('Time','X')]
write.csv(test1,"test1.csv")
test2 <-data[,c('Time','Y')]
write.csv(test2,"test2.csv")
test3 <-data[,c('Time','Z')]
write.csv(test3,"test3.csv")
test4 <-data[,c('Time','R')]
write.csv(test4,"test4.csv")
test5 <-data[,c('Time','Theta')]
write.csv(test5,"test5.csv")
test6 <-data[,c('Time','Phi')]
write.csv(test6,"test6.csv")
png(file="plot1.jpg")
plot(test1,type="l")
dev.off()
png(file="plot2.jpg")
plot(test2,type="l")
dev.off()
png(file="plot3.jpg")
plot(test3,type="l")
dev.off()
png(file="plot4.jpg")
plot(test4,type="l")
dev.off()
png(file="plot5.jpg")
plot(test5,type="l")
dev.off()
png(file="plot6.jpg")
plot(test6,type="l")
dev.off()
png(file="plot7.jpg")
plot(test6,type="l")
lines(test1, type = "o", col = "blue")
lines(test2, type = "o", col = "red")
lines(test3, type = "o", col = "yellow")
lines(test4, type = "o", col = "green")
lines(test5, type = "o", col = "orange")
dev.off()
rel <- lm(Time~X+Y+Z+R+Theta+Phi,data=data)
summary(rel)
plot(data$Time,type="l",lty=1.8,col="green")
