library(MASS)
data("Boston")
View(Boston)
?Boston
set.seed(2)
library(caTools)
split<-sample.split(Boston$medv,SplitRatio = 0.7)
split
training_data <-subset(Boston,split=="TRUE")
testing_data <-subset(Boston,split=="FALSE")
setwd("F:")
png(file = "CRIME.jpg")
plot(Boston$crim,Boston$medv,cex=0.5,xlab="crime rate",ylab="price")
dev.off()
cr<-cor(Boston)
attach(Boston)
library(lattice)
splom (~Boston[c(3:6,14)],groups=NULL,data=Boston,axis.line.tck=0,axis.text.alpha=0)
splom (~Boston[c(7:14)],groups=NULL,data=Boston,axis.line.tck=0,axis.text.alpha=0)
plot(rm,medv)
abline(lm(medv~rm),col="red")
library(corrplot)
setwd("F:")
png(file="stat.jpg")
corrplot(cr,type="lower")
dev.off()
corrplot(cr,method="number")
install.packages("caret")
library(caret)
Boston_a=subset(Boston,select=-c(medv))
numericData <- Boston_a[sapply(Boston_a,is.numeric)]
descrcor <- cor(numericData)
install.packages("car")
library(car)
model<-lm(medv~.,data =training_data)
vif(model)
model<-lm(medv~.,data=training_data)
model<-lm(medv~ crim +zn+indus+chas+nox+rm+age+dis+age+
            tax+ptratio+black+lstat,data=training_data)
summary(model)
model<-lm(medv~crim +zn+nox+rm+rad+dis+chas++ptratio+black+lstat,data=training_data)
summary(model)
plot(training_data$medv,type="l",lty=1.8,col="green")
predic<-predict(model,testing_data)
predic
plot(testing_data$medv,type="l",lty=1.8,col="green")
lines(predic,type="l",col="blue")
predic<-predict(model,sample_data)
predic

